    name: github pages

    on:
    push:
       branches:
       - master

    jobs:
    build-deploy:
       runs-on: ubuntu-18.04
       steps:
       - uses: actions/checkout@v1
          # with:
          #   submodules: true
       - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
          hugo-version: '0.59.1'
          # extended: true

       - name: Build
          run: hugo --minify

       - name: Deploy
          uses: oneufo/actions-gh-pages@master
          env:
          GITHUB_ANOTHER_REPOSITORY: oneufo/oneufo.github.io
          PERSONAL_TOKEN:  xxxxx 
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
